### ISSUE TITLE
UTF-8 BOM handling

### ISSUE THREAD

**Issue by jhihn** [pensierinmusica/firstline#5]
This is not working with a file having a UTF-8 BOM
Given:
![screen shot 2017-08-14 at 3 10 03 pm](https://user-images.githubusercontent.com/5502325/29287226-bf2b06c0-8102-11e7-873b-4555ad7e72d9.png)

I expected it to return "review_id,review_date,comment"
But It returned everything as the first line.

**Comment by pensierinmusica** [comment]
Do you want to send a pr?

**Comment by jhihn** [comment]
No, that's too much work. Just change line 23 to
 resolve(acc.slice( (acc.length > 2 && acc.charCodeAt(0) == 0xFEFF) ? 1 : 0, pos) );

**Comment by jhihn** [comment]
As an aside, I am having issues reading excel UTF-8 CSVs.Unforunately, they use \r ro indicate end line.

I'd recommend adding an optional separator to the function call, defaulting to \n, of course.

**Comment by NoahRoseLedesma** [comment]
<img width="502" alt="screen shot 2018-04-25 at 2 15 28 pm" src="https://user-images.githubusercontent.com/10533913/39273271-26b99470-4893-11e8-8cb8-83e937cd27dd.png">
I came across the same issue. Solved it by hacking together the solution proposed by jhihn

**Comment by pensierinmusica** [comment]
@jhihn and @NoahRoseLedesma what if the BOM is different from `0xFEFF`?

As far as I understand, there can be quite a few variations:
https://en.wikipedia.org/wiki/Byte_order_mark#Byte_order_marks_by_encoding

@jhihn I agree that an optional argument to choose line ending could be provided.

Do you guys want to send a pull request with good test coverage?

**Comment by jhihn** [comment]
Well the BOM varies according to the document type and endianess of the platform it was created on.

Ideally any of the BOMs should trigger starting at byte 1, instead of zero ( if bomArray.contains(acc.charCodeAt(0) ) or similar. 

Do I want to send a PR? Not really. I'm on another project for they past 6 months and not using Node. My JS is getting rusty.

**Comment by pensierinmusica** [comment]
@jhihn on https://github.com/pensierinmusica/firstline/issues/5#issue-250123930 what do you mean by

> it returned everything as the first line

What was your line ending? Also isn't BOM supposed to be at the beginning of the file? If I understand correctly it should not affect line ending detection.

**Comment by jhihn** [comment]
I guess you got it figured out. :-) 
What was your line ending? 
- 0D = \r (MSDOS)
Also isn't BOM supposed to be at the beginning of the file?
- Yes, but it was not properly recognized.
If I understand correctly it should not affect line ending detection.
- I agree, but it does.

Thanks!
